### ISSUE TITLE
Galaxy Buds Pro not showing on devices list

### ISSUE THREAD

**Issue by RafaelSoaresP** [lihaoyun6/AirBattery#27]
<img width="354" alt="image" src="https://github.com/lihaoyun6/AirBattery/assets/33702692/99def676-b21e-45f8-ba94-1dd6b6de4ecb">

Earbuds are connected, but not on the devices list on AirBattery

<img width="295" alt="image" src="https://github.com/lihaoyun6/AirBattery/assets/33702692/10a9ae9f-c1b1-4553-8dd7-e09a5fbfd852">

It's displayed normally on bluetooth menu.

macOS sonoma 14.1.1 on Macbook Pro 2015 15"

**Comment by lihaoyun6** [comment]
<img width="145" alt="image" src="https://github.com/lihaoyun6/AirBattery/assets/16348097/65d924b3-fbb6-41fa-8a65-6b0d57bc3833">  

AirBattery obtains battery usage by reading the broadcast data of BLE peripherals.  
But unfortunately, it seems that your device does not support BLE😢

macOS can read the battery status of your headphone through HFP after connecting to it.  
But AirBattery cannot read these packets because they are encrypted.
