### ISSUE TITLE
Lag on updating the widget 

### ISSUE THREAD

**Issue by Alrazzouq** [lihaoyun6/AirBattery#34]
The widget update is the best of any apps I have used. However, still there is mild lag between it and the system widget, even I use "system" for "Update Interval". It should be perfect especially this is for the same device which the application installed on, not a connected device.
![Screenshot 2024-06-07 at 7 24 43 PM](https://github.com/lihaoyun6/AirBattery/assets/171451552/7fc5dbe5-8ede-4fe7-9743-185480be13fc)

**Comment by lihaoyun6** [comment]
Apple does not refresh all widgets at the same time. Each widget has its own independent "timeline". In fact, users cannot precisely control the refresh time of any widget, and all implementations of this are approximate.  
Even different widgets created by the same App cannot be refreshed at the exact same time, there will always be a delay of several seconds.

**Comment by lihaoyun6** [comment]
Setting the widget update interval to "system" does not mean that it will be refreshed at the same time as other widgets. This option just means that AirBattery will not actively submit refresh requests, and it is entirely up to the system to decide when to refresh.  
Even if two widgets have the same update interval, they may not update at the same time because their timelines may be misaligned

**Comment by Alrazzouq** [comment]
Thank you for the clarification.
