### ISSUE TITLE
AirPods do not merge

### ISSUE THREAD

**Issue by ismslv** [lihaoyun6/AirBattery#70]
In the settings, merge limit is 5%, but earbuds that are both at 100% are shown separately.

<img width="575" alt="image" src="https://github.com/user-attachments/assets/de4508f9-2d49-4e79-b33f-890396af716e">

**Comment by lihaoyun6** [comment]
<img width="83" alt="image" src="https://github.com/user-attachments/assets/d34a158e-39bf-496c-afb7-8a488eb877d9">

![IMG_6416](https://github.com/user-attachments/assets/10a04325-1dd5-4ca9-bb0d-576ccaab7401)

Because the two earbuds have different charging states. This logic is the same as the battery widget in iOS: when the charging states are different (usually meaning one earbud is out of the case and the other is in the case) they will not be combined
